function y = iir_filt_ord3(x,b,a)
% IIR_FILT_ORD3
%
% NOTES
% Filter order is 3 so length of b and a are 7 = 2*3 + 1.
% MATLAB array indices begin with 1.
% a(1) = 1 is the coefficient of y(n) so it is not used.
% b(4) = 0 so it is not included in the summation.
% y(1:6) must be initialized to 0.

N = length(x);
y = zeros(1,N);

for n = 7:N
  y(n) = ...
    + b(1)*x(n) ...
    + b(2)*x(n-1) ...
    + b(3)*x(n-2) ...
    + b(5)*x(n-4) ...
    + b(6)*x(n-5) ...
    + b(7)*x(n-6) ...
    - a(2)*y(n-1) ...
    - a(3)*y(n-2) ...
    - a(4)*y(n-3) ...
    - a(5)*y(n-4) ...
    - a(6)*y(n-5) ...
    - a(7)*y(n-6);
end
    %+ b(4)*x(n-3) ...
